use sys;

CREATE DATABASE BOOTCAMP_2408;
use BOOTCAMP_2408;

CREATE TABLE PRODUCTS (  -- TABLE COLNUMS
SKU VARCHAR (10),
BRAND VARCHAR (20),
PRODUCT_TYPE VARCHAR (10),
PRICE DECIMAL (11,2),
QTY INTEGER
);

DROP TABLE PRODUCTS;   -- DELECT TABLE

SELECT * FROM PRODUCTS; -- SHOW TABLE

INSERT INTO PRODUCTS (SKU, BRAND, PRODUCT_TYPE, PRICE, QTY) -- ADD VALUE
VALUES ('1234','APC', 'TP', 1200.0, 3);

INSERT INTO PRODUCTS (SKU, BRAND, PRODUCT_TYPE, PRICE, QTY)
VALUES ('1235','APC', 'SK', 500.0, 3);

INSERT INTO PRODUCTS (SKU, BRAND, PRODUCT_TYPE, PRICE, QTY)
VALUES ('1236','CDG', 'PT', 4200.0, 3);

INSERT INTO PRODUCTS (SKU, BRAND, PRODUCT_TYPE, PRICE, QTY)
VALUES ('1237','FOG', 'PT', 3200.0, 2);

SELECT * FROM PRODUCTS WHERE BRAND = 'APC'; -- SELECT ONLY APC, LIKE A FILTER

SELECT BRAND , QTY FROM PRODUCTS WHERE PRODUCT_TYPE = 'PT';  -- SELECT 2 THINGS AND FILTER

ALTER TABLE PRODUCTS ADD SEASON VARCHAR(10); -- ADD COLNUMS IN TABLE

UPDATE PRODUCTS SET SEASON = 'SS24' WHERE SKU = '1234'; -- ADD VALUE IN NEW CLONUMS, SEASON 
UPDATE PRODUCTS SET SEASON = 'SS24' WHERE SKU = '1235';
UPDATE PRODUCTS SET SEASON = 'SS24' WHERE SKU = '1236';
UPDATE PRODUCTS SET SEASON = 'SS24' WHERE SKU = '1237';


UPDATE PRODUCTS SET QTY ='1' WHERE SKU='1234'; -- UPDATE VALUE
SELECT * FROM PRODUCTS ;

ALTER TABLE PRODUCTS ADD DISCOUNT_START_DATE DATE;  -- ADD CLONUMS DISCOUNT DATE <DATE> 
UPDATE PRODUCTS SET DISCOUNT_START_DATE = STR_TO_DATE('2024-08-03', '%Y-%m-%d') WHERE SKU = '1234'; -- <STR_TO_DATE> ADD DATE
UPDATE PRODUCTS SET DISCOUNT_START_DATE = STR_TO_DATE('2024-08-03', '%Y-%m-%d') WHERE SKU = '1235'; 
UPDATE PRODUCTS SET DISCOUNT_START_DATE = STR_TO_DATE('2024-08-03', '%Y-%m-%d') WHERE SKU = '1236'; 
UPDATE PRODUCTS SET DISCOUNT_START_DATE = STR_TO_DATE('2024-08-03', '%Y-%m-%d') WHERE SKU = '1237'; 

-- GET DISCOUNT END DATE <DATE_ADD> <INTERVAL 3 WEEK) 
SELECT DATE_ADD(DISCOUNT_START_DATE, INTERVAL 3 WEEK) AS DISCOUNT_END_DATE
, P.SKU
, P.BRAND
, P.PRODUCT_TYPE
, P.DISCOUNT_START_DATE
FROM PRODUCTS P;

-- SUM
SELECT SUM(PRICE)
FROM PRODUCTS;

-- SUM BY SELECT
SELECT SUM(PRICE)
FROM PRODUCTS
WHERE BRAND = 'APC';

--
SELECT BRAND,  COUNT(1) AS NUMBER_OF_SKU, MAX(PRICE) AS MOST_EXPENSIVE
FROM PRODUCTS
WHERE BRAND 
GROUP BY BRAND;
