-- day 4
-- CREATE VIEW
CREATE VIEW DEPARTMENT_EMPLOYMENT_STAT
AS 
SELECT S.DEPT_CODE
, MIN(S.EMPLOYMENT_DATE) AS EARLIEST_EMPLOYMENT_DATE
, MAX(S.EMPLOYMENT_DATE) AS LATEST_EMPLOYMENT_DATE
, SUM(S.SALARY) AS TOTAL_SALARY
, COUNT(1) AS NUM_OF_STAFF
FROM STAFFS S
GROUP BY S.DEPT_CODE
;
-- SELECT VIEW
SELECT * FROM DEPARTMENT_EMPLOYMENT_STAT;
-- VIEW -> REAL-TIME LOOKUP THE PHYSICAL TABLE
-- 1. NO IMPACT TO DATABASE WORKLOAD, BECAUSE THE SQL IS REAL-TIME EXECUTION
-- 2. BETTER FOR DATA SECURITY MANAGEMENT (TABLE/VIEW ACCESS RIGHT), BECAUSE TEAMS HAVE DIFFERENT DATA OWNERSHIP

SELECT * FROM CUSTOMER_VIP_INFO;

CREATE VIEW CUSTOMER_VIP_INFO
AS
SELECT ID, VIP
FROM CUSTOMER;


CREATE TABLE DEPT_INFO_REPORT (
	DEPT_CODE VARCHAR(2),
	AVG_SALARY DECIMAL(11, 2)
);

DROP PROCEDURE IF EXISTS INSERT_DEPT_INFO_REPORT;

-- PROCEDURE CODE
DELIMITER //

CREATE PROCEDURE INSERT_DEPT_INFO_REPORT() -- IN STAFF_ID INTEGER

BEGIN
	DECLARE done INT DEFAULT 0;
    DECLARE v_dept_code VARCHAR(2);
    DECLARE v_avg_salary DECIMAL(11, 2);
    
	DECLARE dept_cursor CURSOR FOR
        SELECT DEPT_CODE, ROUND(AVG(SALARY), 2)
        FROM STAFFS
        GROUP BY DEPT_CODE;
        
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
    
    DELETE FROM DEPT_INFO_REPORT;
    
     -- Open the cursor
    OPEN dept_cursor;
    dept_loop: LOOP 
        FETCH dept_cursor INTO v_dept_code, v_avg_salary;
        IF done THEN
            LEAVE dept_loop;
        END IF;
        
        INSERT INTO DEPT_INFO_REPORT (DEPT_CODE, AVG_SALARY) VALUES (v_dept_code, v_avg_salary);
    END LOOP;
    CLOSE dept_cursor;
END;
//

DELIMITER ;

-- CALL PROCEDURE
CALL INSERT_DEPT_INFO_REPORT();
-- SELECT THE RESULT
SELECT * FROM DEPT_INFO_REPORT;


CREATE TABLE DEPT_STAFF_COUNT (
	DEPT_CODE VARCHAR(2),
    COUNT INT
);


DROP TRIGGER IF EXISTS DEPT_STAFF_COUNT_TRIGGER;

DELIMITER //

CREATE TRIGGER DEPT_STAFF_COUNT_TRIGGER
AFTER INSERT ON STAFFS
FOR EACH ROW
BEGIN
    DECLARE notfound INT DEFAULT 0;
    DECLARE v_dept_code VARCHAR(2);
    DECLARE v_avg_salary DECIMAL(11, 2);
    DECLARE v_found INT DEFAULT 0;
    
	DECLARE dept_cursor CURSOR FOR
        SELECT 1
        FROM DEPT_STAFF_COUNT
        WHERE DEPT_CODE = NEW.DEPT_CODE;
        
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET notfound = 1;
    
    DELETE FROM DEPT_INFO_REPORT;
    
     -- Open the cursor
    OPEN dept_cursor;
    dept_loop: LOOP 
        FETCH dept_cursor INTO v_found;
        IF notfound THEN
			INSERT INTO DEPT_STAFF_COUNT (DEPT_CODE, COUNT) VALUES (NEW.DEPT_CODE, 1);
            LEAVE dept_loop;
        END IF;
        UPDATE DEPT_STAFF_COUNT SET COUNT = COUNT + 1 WHERE DEPT_CODE = NEW.DEPT_CODE;
        LEAVE dept_loop;
    END LOOP;
    CLOSE dept_cursor;
END;
//

DELIMITER ;

INSERT INTO STAFFS (ID, STAFF_NAME, GENDER, SALARY, STAFF_EMAIL, DEPT_CODE) 
	VALUES (100, 'VINCENT WONG', 'M', 30000.5, 'VINCENTWONG@gmail.com', 'IT');
INSERT INTO STAFFS (ID, STAFF_NAME, GENDER, SALARY, STAFF_EMAIL, DEPT_CODE) 
	VALUES (101, 'SALLY WONG', 'M', 30000.5, 'SALLY@gmail.com', 'IT');
INSERT INTO STAFFS (ID, STAFF_NAME, GENDER, SALARY, STAFF_EMAIL, DEPT_CODE) 
	VALUES (102, 'BETTY WONG', 'M', 30000.5, 'BETTY@gmail.com', 'HR');
SELECT * FROM DEPT_STAFF_COUNT;